/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pnrs_rtrk_myapplication_MyNDK */

#ifndef _Included_pnrs_rtrk_myapplication_MyNDK
#define _Included_pnrs_rtrk_myapplication_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pnrs_rtrk_myapplication_MyNDK
 * Method:    convert
 * Signature: (DI)I
 */
JNIEXPORT jint JNICALL Java_pnrs_rtrk_myapplication_MyNDK_convert
  (JNIEnv *, jobject, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
